[package]
name = "interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]
name = "interface"

[dependencies]
anchor-lang = "0.27.0"
anchor-spl = "0.27.0"
